### ISSUE TITLE
Sending reminder Mail

### ISSUE THREAD

**Issue by Sebastian1515** [Sebastian1515/ILMO#3]
Sending the daily reminder mail causes an error because of the changed signature of method send_mail in class/mail.php
`Fatal error: Uncaught TypeError: wordwrap(): Argument #1 ($string) must be of type string, array given in C:\xampp\htdocs\ILMO\class\mail.php:71 Stack trace: #0 C:\xampp\htdocs\ILMO\class\mail.php(71): wordwrap(Array, 70, '\r\n') #1 C:\xampp\htdocs\ILMO\class\loan.php(270): Mail->send_mail(Array, 'Erinnerung: Dei...', Array) #2 C:\xampp\htdocs\ILMO\class\loan.php(221): Loan->send_reminder(Array) #3 C:\xampp\htdocs\ILMO\index.php(45): Loan->send_todays_mails() #4 {main} thrown in C:\xampp\htdocs\ILMO\class\mail.php on line 71`

**Comment by Sebastian1515** [comment]
Closed in #91c203e
